<?php
/**
* define html types variables
*
*
 * @package   mod_modmendeley
 * @copyright 2011 María del Mar Jiménez Torres (mjimenez@fidesol.org) - Fundación I+D del Software Libre (www.fidesol.org)
 \* @license   http://www.apache.org/licenses/LICENSE-2.0.html Apache License, Version 2.0
*/

define("TITLE", "<td class='document_edit_label'>Title</td><td class='document_edit_field'><textarea id='post_title_VARIABLE' class='edit_field1 value_title' name='VARIABLE[title]' cols='38' style='height:3em;font:11px,arial;' tabindex='1'></textarea></td>");
define("AUTHORS", "<td class='document_edit_label'>Authors</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddBillauthors' class='edit_field1 value_authors' name='VARIABLE[authors]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("CODE", "<td class='document_edit_label'>Code</td><td class='document_edit_field'><input id='' class='edit_field1 value_code' name='VARIABLE[code]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("CODE_VOLUME", "<td class='document_edit_label'>Code Volume</td><td class='document_edit_field'><input id='' class='edit_field1_short value_codeVolume' name='VARIABLE[codeVolume]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("LEGISLATIVE_BODY", "<td class='document_edit_label'>Legislative Body</td><td class='document_edit_field'><input id='' class='edit_field1 value_publisher' name='VARIABLE[publisher]' value='' type='text' tabindex='1'></td>");
define("CITY", "<td class='document_edit_label'>City</td><td class='document_edit_field'><input id='' class='edit_field1_short value_city' name='VARIABLE[city]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("CODE_NUMBER", "<td class='document_edit_label'>Code Number</td><td class='document_edit_field'><input id='' class='edit_field1_short value_codeNumber' name='VARIABLE[codeNumber]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("CODE_PAGES", "<td class='document_edit_label'>Code Pages</td><td class='document_edit_field'><input id='' class='edit_field1_short value_pages' name='VARIABLE[pages]' value='' type='text' tabindex='1' maxlength='50' onkeydown=''></td>");
define("YEAR", "<td class='document_edit_label'>Year</td><td class='document_edit_field'><input id='' class='edit_field1_short value_year' name='VARIABLE[year]' value='' type='text' tabindex='1' maxlength='11' onkeydown=''></td>");
define("URL","<td class='document_edit_label'>URL</td><td class='document_edit_field'><textarea id='' class='edit_field1 value_website' name='VARIABLE[website]' cols='38' style='height:3em;font:11px,arial;' tabindex='1'></textarea></td>");
define("KEYWORDS","<td class='document_edit_label'>Keywords</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddBillkeywords' class='edit_field1 value_keywords' name='VARIABLE[keywords]' cols='38' style='height:3em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Author-supplied keywords (Keyword 1; Keyword 2; ...)</div></div></td>");
define("BOOK", "<td class='document_edit_label'>Book</td><td class='document_edit_field'><input id='' class='edit_field1 value_published_in' name='VARIABLE[published_in]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("DATE_DECIDED","<td class='document_edit_label'>Date Decided</td><td class='document_edit_field'><input id='' class='edit_field1 value_lastUpdate' name='VARIABLE[lastUpdate]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("VERSION", "<td class='document_edit_label'>Version</td><td class='document_edit_field'><input id='' class='edit_field1_short value_revision' name=' VARIABLE[revision]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("PROC_TITLE", "<td class='document_edit_label'>Proc. Title</td><td class='document_edit_field'><input id='' class='edit_field1 value_published_in' name='VARIABLE[published_in]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ENCYCLOPEDIA", "<td class='document_edit_label'>Encyclopedia</td><td class='document_edit_field'><input id='' class='edit_field1 value_published_in' name='VARIABLE[published_in]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("DISTRIBUTOR", "<td class='document_edit_label'>Distributor</td><td class='document_edit_field'><input id='' class='edit_field1 value_publisher' name='VARIABLE[publisher]' value='' type='text' tabindex='1'></td>");
define("PUBLISHER", "<td class='document_edit_label'>Publisher</td><td class='document_edit_field'><input id='' class='edit_field1 value_publisher' name='VARIABLE[publisher]' value='' type='text' tabindex='1'></td>");
define("JOURNAL", "<td class='document_edit_label'>Journal</td><td class='document_edit_field'><input id='' class='edit_field1 value_published_in' name='VARIABLE[published_in]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INVENTORS", "<td class='document_edit_label'>Inventors</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddPatentauthors' class='edit_field1 value_authors' name='VARIABLE[authors]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("ISSUER", "<td class='document_edit_label'>Issuer</td><td class='document_edit_field'><input id='' class='edit_field1 value_publisher' name='VARIABLE[publisher]' value='' type='text' tabindex='1'></td>");
define("ASSIGNEE", "<td class='document_edit_label'>Assignee</td><td class='document_edit_field'><input id='' class='edit_field1 value_owner' name='VARIABLE[owner]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SOURCE", "<td class='document_edit_label'>Source</td><td class='document_edit_field'><input id='' class='edit_field1 value_publisher' name='VARIABLE[publisher]' value='' type='text' tabindex='1'></td>");
define("STATUTE_NUMBER", "<td class='document_edit_label'>Statute Number</td><td class='document_edit_field'><input id='' class='edit_field1_short value_revision' name='VARIABLE[revision]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("DIRECTORS", "<td class='document_edit_label'>Directors</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddTelevisionBroadcastauthors' class='edit_field1 value_authors' name='VARIABLE[authors]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("UNIVERSITY", "<td class='document_edit_label'>University</td><td class='document_edit_field'><input id='' class='edit_field1 value_institution' name='VARIABLE[institution]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ABSTRACT", "<td class='document_edit_label'>Abstract</td><td class='document_edit_field'><textarea id='' class='edit_field1 value_abstract' name='VARIABLE[abstract]' cols='38' style='height:6em;font:11px,arial;' tabindex='1'></textarea></td>");
define("ADVISOR", "<td class='document_edit_label'>Advisor</td><td class='document_edit_field'><input id='' class='edit_field1 value_advisor' name='VARIABLE[advisor]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("APPLICATION_NUMBER", "<td class='document_edit_label'>Application Number</td><td class='document_edit_field'><input id='' class='edit_field1 value_applicationNumber' name='VARIABLE[applicationNumber]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("COLUMN","<td class='document_edit_label'>Column</td><td class='document_edit_field'><input id='' class='edit_field1 value_articleColumn' name='VARIABLE[articleColumn]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ARXIV_ID","<td class='document_edit_label'>ArXiv ID</td><td class='document_edit_field'><input id='' class='lookup_field value_arxiv' name='VARIABLE[arxiv]' value='' type='text'></td>");
define("CAST", "<td class='document_edit_label'>Cast</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddBillcast' class='edit_field1 value_cast' name='VARIABLE[cast]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("CHAPTER", "<td class='document_edit_label'>Chapter</td><td class='document_edit_field'><input id='' class='edit_field1_short value_chapter' name='VARIABLE[chapter]' value='' type='text' tabindex='1' maxlength='10' onkeydown=''></td>");
define("CITATION_KEY", "<td class='document_edit_label'>Citation Key</td><td class='document_edit_field'><input id='' class='edit_field1_short value_citation_key' name='VARIABLE[citation_key]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("CODE_SECTION", "<td class='document_edit_label'>Code Section</td><td class='document_edit_field'><input id='' class='edit_field1 value_codeSection' name='VARIABLE[codeSection]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("COMMITEE", "<td class='document_edit_label'>Committee</td><td class='document_edit_field'><input id='' class='edit_field1 value_committee' name='VARIABLE[committee]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("COUNSEL", "<td class='document_edit_label'>Counsel</td><td class='document_edit_field'><input id='' class='edit_field1 value_counsel' name='VARIABLE[counsel]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("COUNTRY", "<td class='document_edit_label'>Country</td><td class='document_edit_field'><input id='' class='edit_field1_short value_country' name='VARIABLE[country]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ADDITIONAL_DATE", "<td class='document_edit_label'>Additional Date</td><td class='document_edit_field'><input id='' class='edit_field1 value_date' name='VARIABLE[date]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("DATE_ACCESSED", "<td class='document_edit_label'>Date Accessed</td><td class='document_edit_field'><input id='' class='edit_field1 value_dateAccessed' name='VARIABLE[dateAccessed]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("DAY", "<td class='document_edit_label'>Day</td><td class='document_edit_field'><input id='' class='edit_field1_short value_day' name='VARIABLE[day]' value='' type='text' tabindex='1' maxlength='11' onkeydown=''></td>");
define("DEPARTMENT", "<td class='document_edit_label'>Department</td><td class='document_edit_field'><input id='' class='edit_field1 value_department' name='VARIABLE[department]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("DOI", "<td class='document_edit_label'>DOI</td><td class='document_edit_field'><input id='' class='lookup_field value_doi' name='VARIABLE[doi]' value='' type='text'></td>");
define("EDITION", "<td class='document_edit_label'>Edition</td><td class='document_edit_field'><input id='' class='edit_field1_short value_edition' name='VARIABLE[edition]' value='' type='text' tabindex='1' maxlength='10' onkeydown=''></td>");
define("EDITORS", "<td class='document_edit_label'>Editors</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddBilleditors' class='edit_field1 value_editors' name='VARIABLE[editors]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("GENRE", "<td class='document_edit_label'>Genre</td><td class='document_edit_field'><input id='' class='edit_field1 value_genre' name='VARIABLE[genre]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INSTITUTION", "<td class='document_edit_label'>Institution</td><td class='document_edit_field'><input id='' class='edit_field1 value_institution' name='VARIABLE[institution]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INTERNATIONAL_AUTHOR", "<td class='document_edit_label'>International Author</td><td class='document_edit_field'><input id='' class='edit_field1 value_internationalAuthor' name='VARIABLE[internationalAuthor]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INTERNATIONAL_NUMBER", "<td class='document_edit_label'>International Number</td><td class='document_edit_field'><input id='' class='edit_field1_short value_internationalNumber' name='VARIABLE[internationalNumber]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INTERNATIONAL_TITLE", "<td class='document_edit_label'>International Title</td><td class='document_edit_field'><input id='' class='edit_field1 value_internationalTitle' name='VARIABLE[internationalTitle]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INTERNATIONAL_CLASSIFICATION", "<td class='document_edit_label'>International Classification</td><td class='document_edit_field'><input id='' class='edit_field1_short value_internationalUserType' name='VARIABLE[internationalUserType]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ISBN", "<td class='document_edit_label'>ISBN</td><td class='document_edit_field'><input id='' class='edit_field1 value_isbn' name='VARIABLE[isbn]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ISSN", "<td class='document_edit_label'>ISSN</td><td class='document_edit_field'><input id='' class='edit_field1 value_issn' name='VARIABLE[issn]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("ISSUE", "<td class='document_edit_label'>Issue</td><td class='document_edit_field'><input id='' class='edit_field1_short value_issue' name='VARIABLE[issue]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("LANGUAGE", "<td class='document_edit_label'>Language</td><td class='document_edit_field'><input id='' class='edit_field1_short value_language' name='VARIABLE[language]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("LAST_UPDATED", "<td class='document_edit_label'>Last Updated</td><td class='document_edit_field'><input id='' class='edit_field1 value_lastUpdate' name='VARIABLE[lastUpdate]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("LEGAL_STATUS", "<td class='document_edit_label'>Legal Status</td><td class='document_edit_field'><input id='' class='edit_field1 value_legalStatus' name='VARIABLE[legalStatus]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("LENGTH", "<td class='document_edit_label'>Length</td><td class='document_edit_field'><input id='' class='edit_field1_short value_length' name='VARIABLE[length]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("MEDIUM", "<td class='document_edit_label'>Medium</td><td class='document_edit_field'><input id='' class='edit_field1 value_medium' name='VARIABLE[medium]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("MONTH", "<td class='document_edit_label'>Month</td><td class='document_edit_field'><input id='' class='edit_field1_short value_month' name='VARIABLE[month]' value='' type='text' tabindex='1' maxlength='11' onkeydown=''></td>");
define("ORIGINAL_PUBLICATION", "<td class='document_edit_label'>Original Publication</td><td class='document_edit_field'><input id='' class='edit_field1 value_original_publication' name='VARIABLE[original_publication]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("OWNER", "<td class='document_edit_label'>Owner</td><td class='document_edit_field'><input id='' class='edit_field1 value_owner' name='VARIABLE[owner]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("PMID", "<td class='document_edit_label'>PMID</td><td class='document_edit_field'><input id='' class='lookup_field value_pmid' name='VARIABLE[pmid]' value='' type='text'></td>");
define("PRODUCERS", "<td class='document_edit_label'>Producers</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddBillproducers' class='edit_field1 value_producers' name='VARIABLE[producers]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("PUBLIC_LAW_NO", "<td class='document_edit_label'>Public Law No.</td><td class='document_edit_field'><input id='' class='edit_field1_short value_publicLawNumber' name='VARIABLE[publicLawNumber]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("PUBLICATION", "<td class='document_edit_label'>Publication</td><td class='document_edit_field'><input id='' class='edit_field1 value_published_in' name='VARIABLE[published_in]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("REPRINT_EDITION", "<td class='document_edit_label'>Reprint Edition</td><td class='document_edit_field'><input id='' class='edit_field1_short value_reprint_edition' name='VARIABLE[reprint_edition]' value='' type='text' tabindex='1' maxlength='10' onkeydown='Mendeley.Publication.checkFieldLength(event,this,10);return true;'></td>");
define("REVIEWED_ITEM", "<td class='document_edit_label'>Reviewed Item</td><td class='document_edit_field'><input id='' class='edit_field1 value_reviewedArticle' name='VARIABLE[reviewedArticle]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("NUMBER", "<td class='document_edit_label'>Number</td><td class='document_edit_field'><input id='' class='edit_field1_short value_revision' name='VARIABLE[revision]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SECTIONS", "<td class='document_edit_label'>Sections</td><td class='document_edit_field'><input id='' class='edit_field1 value_sections' name='VARIABLE[sections]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SERIES", "<td class='document_edit_label'>Series</td><td class='document_edit_field'><input id='' class='edit_field1 value_series' name='VARIABLE[series]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SERIES_EDITOR", "<td class='document_edit_label'>Series Editor</td><td class='document_edit_field'><input id='' class='edit_field1 value_seriesEditor' name='VARIABLE[seriesEditor]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SERIES_NUMBER", "<td class='document_edit_label'>Series Number</td><td class='document_edit_field'><input id='' class='edit_field1_short value_seriesNumber' name='VARIABLE[seriesNumber]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SESSION", "<td class='document_edit_label'>Session</td><td class='document_edit_field'><input id='' class='edit_field1 value_session' name='VARIABLE[session]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SHORT_TITLE", "<td class='document_edit_label'>Short Title</td><td class='document_edit_field'><input id='' class='edit_field1 value_short_title' name='VARIABLE[short_title]' value='' type='text' tabindex='1' maxlength='50' onkeydown='Mendeley.Publication.checkFieldLength(event,this,50);return true;'></td>");
define("TYPE_OF_WORK", "<td class='document_edit_label'>Type of Work</td><td class='document_edit_field'><input id='' class='edit_field1_short value_source_type' name='VARIABLE[source_type]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("TIME", "<td class='document_edit_label'>Time</td><td class='document_edit_field'><input id='UaddBilltime' class='edit_field1_short value_time' name='VARIABLE[time]' value='' type='text' tabindex='1' placeholder='HH:MM:SS'></td>");
define("TRANSLATORS", "<td class='document_edit_label'>Translators</td><td class='document_edit_field'><div style='position:relative;overflow:hidden;display:inline-block;' class='form-prompt-wrapper form-prompt-textarea'><textarea id='UaddBilltranslators' class='edit_field1 value_translators' name='VARIABLE[translators]' cols='38' style='height:5em;font:11px,arial;' tabindex='1'></textarea><div class='form-prompt-text' style='position: absolute; top: 3px; left: 3px; z-index: 1000; '>Last Name, First Names<br>Last Name, First Names...</div></div></td>");
define("TYPE", "<td class='document_edit_label'>Type</td><td class='document_edit_field'><input id='' class='edit_field1_short value_userType' name='VARIABLE[userType]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("VOLUME", "<td class='document_edit_label'>Volume</td><td class='document_edit_field'><input id='' class='edit_field1_short value_volume' name='VARIABLE[volume]' value='' type='text' tabindex='1' maxlength='10' onkeydown='Mendeley.Publication.checkFieldLength(event,this,10);return true;'></td>");
define("SERIES_VOLUME", "<td class='document_edit_label'>Series Volume</td><td class='document_edit_field'><input id='' class='edit_field1_short value_volume' name='VARIABLE[volume]' value='' type='text' tabindex='1' maxlength='10' onkeydown='Mendeley.Publication.checkFieldLength(event,this,10);return true;'></td>");
define("DATE_ENACTED", "<td class='document_edit_label'>Date Enacted</td><td class='document_edit_field'><input id='' class='edit_field1 value_lastUpdate' name='VARIABLE[lastUpdate]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("INTERNATIONAL_SOURCE", "<td class='document_edit_label'>International Source</td><td class='document_edit_field'><input id='' class='edit_field1 value_internationalTitle' name='VARIABLE[internationalTitle]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("SERIES_TITLE", "<td class='document_edit_label'>Series Title</td><td class='document_edit_field'><input id='' class='edit_field1 value_published_in' name='VARIABLE[published_in]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("PAGES", "<td class='document_edit_label'>Pages</td><td class='document_edit_field'><input id='' class='edit_field1_short value_pages' name='VARIABLE[pages]' value='' type='text' tabindex='1' maxlength='50' onkeydown='Mendeley.Publication.checkFieldLength(event,this,50);return true;'></td>");
define("REVISION_NUMBER","<td class='document_edit_label'>Revision Number</td><td class='document_edit_field'><input id='' class='edit_field1_short value_revision' name='VARIABLE[revision]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("REPORTERS","<td class='document_edit_label'>Reporters</td><td class='document_edit_field'><input id='' class='edit_field1_short value_revision' name='VARIABLE[reporters]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");
define("FORMAT","<td class='document_edit_label'>Format</td><td class='document_edit_field'><input id='' class='edit_field1_short value_revision' name='VARIABLE[format]' value='' type='text' tabindex='1' maxlength='255' onkeydown=''></td>");

$document_type = array("bill" => array("Primary" => array("title", "authors", "code", "code_volume", "legislative_body", "city", "code_number", "code_pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code_section", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "book" => array("Primary" => array("title", "authors", "publisher", "editors", "city", "edition", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "book_section" => array("Primary" => array("title", "authors", "book", "editors", "publisher", "city", "edition", "chapter", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "case" => array("Primary" => array("title", "reporters", "date_decided", "counsel", "volume", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city", "code", "code_number", "code_section", "code_volume", "commitee", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "publisher", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type")),
                       "computer_program" => array("Primary" => array("title", "authors", "version", "publisher", "city", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pages", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "conference_proceedings" => array("Primary" => array("title", "authors", "proc_title", "editors", "publisher", "city", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "encyclopedia_article" => array("Primary" => array("title", "authors", "encyclopedia", "publisher", "series_number", "edition", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "film" => array("Primary" => array("title", "directors", "country", "distributor", "length", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "format", "volume")),
                       "generic" => array("Primary" => array("title", "authors", "type_of_work", "publisher", "city", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "number", "sections", "series", "series_editor", "series_number", "session", "short_title", "time", "translators", "type", "volume")),
                       "hearing" => array("Primary" => array("title", "authors", "commitee", "city", "publisher", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "journal_article" => array("Primary" => array("title", "authors", "journal", "volume", "issue", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publisher", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type")),
                       "magazine_article" => array("Primary" => array("title", "authors", "publication", "city", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publisher", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "newspaper_article" => array("Primary" => array("title", "authors", "publication", "city", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publisher", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "patent" => array("Primary" => array("title", "inventors", "issuer", "institution", "country", "assignee", "number", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "pmid", "producers", "public_law_no", "source", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "report" => array("Primary" => array("title", "authors", "institution", "city", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "publisher", "reprint_edition", "reviewed_item", "number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "series_volume")),
                       "statute" => array("Primary" => array("title", "authors", "code", "country", "source", "statute_number", "code_number", "public_law_no", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code_section", "code_volume", "commitee", "counsel", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_source", "international_classification", "isbn", "issn", "issue", "language", "date_enacted", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "television_broadcast" => array("Primary" => array("title", "directors", "country", "distributor", "length", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city" , "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "medium", "month", "original_publication", "owner", "pages", "pmid", "producers", "public_law_no", "publication", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "format", "volume")),
                       "thesis" => array("Primary" => array("title", "authors", "type", "department", "university", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city" , "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "doi", "edition", "editors", "genre", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "publication", "publisher", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "volume")),
                       "web_page" => array("Primary" => array("title", "authors", "publication", "date_accessed", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "city", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "day", "department", "doi", "edition", "editors", "genre", "institution", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pages", "pmid", "producers", "public_law_no", "publisher", "reprint_edition", "reviewed_item", "revision_number", "sections", "series", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume")),
                       "working_paper" => array("Primary" => array("title", "authors", "series", "institution", "city", "number", "pages", "year", "url", "keywords"), "Additional" => array("abstract", "advisor", "application_number", "column", "arxiv_id", "cast", "chapter", "citation_key", "code", "code_number", "code_section", "code_volume", "commitee", "counsel", "country", "additional_date", "date_accessed", "day", "department", "doi", "edition", "editors", "genre", "international_author", "international_number", "international_title", "international_classification", "isbn", "issn", "issue", "language", "last_updated", "legal_status", "length", "medium", "month", "original_publication", "owner", "pmid", "producers", "public_law_no", "series_title" ,"publisher", "reprint_edition", "reviewed_item", "sections", "series_editor", "series_number", "session", "short_title", "type_of_work", "time", "translators", "type", "volume"))
                    );

?>

